### ISSUE TITLE
Changing pin to use

### ISSUE THREAD

**Issue by EggrollOfDestruction** [meawoppl/eepromTool-ds2433#4]
Hey Matty, is there a way to change the pin that is used? I tried changing the line `OneWire ds(12);` to `OneWire ds(13);` and I'm using [slayton's cartridge writer](https://github.com/slaytonrnd/CartridgeWriter) but the program seems to have a problem if I change the pin. I would normally think that the problem would be with the cartridge writer program but as far as I can tell the onewireProxy script is what is actually interfacing with the board. Is this an issue with eepromTool or should I be looking at the cartridge writer you think? Any tips?

**Comment by EggrollOfDestruction** [comment]
Nevermind, it turns out I have a bad pin 13 on that particular arduino, it works with other ports and on another board it works with pin 13. Doh!

**Comment by meawoppl** [comment]
It seems you know me somehow.  I hope you find this tool useful!
